from typing import NamedTuple, Dict, Optional

class ItemData(NamedTuple):
    code: int
    category: str = "Item"
    progression: bool = False
    useful: bool = False
    trap: bool = False

ITEM_ID_OFFSET = 200000

item_table: Dict[str, ItemData] = {
    "Bug Badge": ItemData(200801, "Badges", progression=True, useful=False),
    "Cliff Badge": ItemData(200802, "Badges", progression=True, useful=False),
    "Rumble Badge": ItemData(200803, "Badges", progression=True, useful=False),
    "Plant Badge": ItemData(200804, "Badges", progression=True, useful=False),
    "Voltage Badge": ItemData(200805, "Badges", progression=True, useful=False),
    "Fairy Badge": ItemData(200806, "Badges", progression=True, useful=False),
    "Psychic Badge": ItemData(200807, "Badges", progression=True, useful=False),
    "Iceberg Badge": ItemData(200808, "Badges", progression=True, useful=False),

    "Master Ball": ItemData(200001, "Item", progression=False, useful=False),
    "Ultra Ball": ItemData(200002, "Item", progression=False, useful=False),
    "Great Ball": ItemData(200003, "Item", progression=False, useful=False),
    "Poké Ball": ItemData(200004, "Item", progression=False, useful=False),
    "Safari Ball": ItemData(200005, "Item", progression=False, useful=False),
    "Net Ball": ItemData(200006, "Item", progression=False, useful=False),
    "Dive Ball": ItemData(200007, "Item", progression=False, useful=False),
    "Nest Ball": ItemData(200008, "Item", progression=False, useful=False),
    "Repeat Ball": ItemData(200009, "Item", progression=False, useful=False),
    "Timer Ball": ItemData(200010, "Item", progression=False, useful=False),
    "Luxury Ball": ItemData(200011, "Item", progression=False, useful=False),
    "Premier Ball": ItemData(200012, "Item", progression=False, useful=False),
    "Dusk Ball": ItemData(200013, "Item", progression=False, useful=False),
    "Heal Ball": ItemData(200014, "Item", progression=False, useful=False),
    "Quick Ball": ItemData(200015, "Item", progression=False, useful=False),
    "Cherish Ball": ItemData(200016, "Item", progression=False, useful=False),

    "Potion": ItemData(200017, "Item", progression=False, useful=False),
    "Antidote": ItemData(200018, "Item", progression=False, useful=False),
    "Burn Heal": ItemData(200019, "Item", progression=False, useful=False),
    "Ice Heal": ItemData(200020, "Item", progression=False, useful=False),
    "Awakening": ItemData(200021, "Item", progression=False, useful=False),
    "Paralyze Heal": ItemData(200022, "Item", progression=False, useful=False),
    "Full Restore": ItemData(200023, "Item", progression=False, useful=False),
    "Max Potion": ItemData(200024, "Item", progression=False, useful=False),
    "Hyper Potion": ItemData(200025, "Item", progression=False, useful=False),
    "Super Potion": ItemData(200026, "Item", progression=False, useful=False),
    "Full Heal": ItemData(200027, "Item", progression=False, useful=False),
    "Revive": ItemData(200028, "Item", progression=False, useful=False),
    "Max Revive": ItemData(200029, "Item", progression=False, useful=False),
    "Fresh Water": ItemData(200030, "Item", progression=False, useful=False),
    "Soda Pop": ItemData(200031, "Item", progression=False, useful=False),
    "Lemonade": ItemData(200032, "Item", progression=False, useful=False),
    "Moomoo Milk": ItemData(200033, "Item", progression=False, useful=False),
    "Energy Powder": ItemData(200034, "Item", progression=False, useful=False),
    "Energy Root": ItemData(200035, "Item", progression=False, useful=False),
    "Heal Powder": ItemData(200036, "Item", progression=False, useful=False),
    "Revival Herb": ItemData(200037, "Item", progression=False, useful=False),
    "Ether": ItemData(200038, "Item", progression=False, useful=False),
    "Max Ether": ItemData(200039, "Item", progression=False, useful=False),
    "Elixir": ItemData(200040, "Item", progression=False, useful=False),
    "Max Elixir": ItemData(200041, "Item", progression=False, useful=False),
    "Lava Cookie": ItemData(200042, "Item", progression=False, useful=False),
    "Berry Juice": ItemData(200043, "Item", progression=False, useful=False),
    "Sacred Ash": ItemData(200044, "Item", progression=False, useful=False),
    "HP Up": ItemData(200045, "Item", progression=False, useful=False),
    "Protein": ItemData(200046, "Item", progression=False, useful=False),
    "Iron": ItemData(200047, "Item", progression=False, useful=False),
    "Carbos": ItemData(200048, "Item", progression=False, useful=False),
    "Calcium": ItemData(200049, "Item", progression=False, useful=False),
    "Rare Candy": ItemData(200050, "Item", progression=False, useful=False),
    "PP Up": ItemData(200051, "Item", progression=False, useful=False),
    "Zinc": ItemData(200052, "Item", progression=False, useful=False),
    "PP Max": ItemData(200053, "Item", progression=False, useful=False),
    "Guard Spec.": ItemData(200055, "Item", progression=False, useful=False),
    "Dire Hit": ItemData(200056, "Item", progression=False, useful=False),
    "X Attack": ItemData(200057, "Item", progression=False, useful=False),
    "X Defense": ItemData(200058, "Item", progression=False, useful=False),
    "X Speed": ItemData(200059, "Item", progression=False, useful=False),
    "X Accuracy": ItemData(200060, "Item", progression=False, useful=False),
    "X Sp. Atk": ItemData(200061, "Item", progression=False, useful=False),
    "X Sp. Def": ItemData(200062, "Item", progression=False, useful=False),
    "Escape Rope": ItemData(200078, "Item", progression=False, useful=False),
    "Repel": ItemData(200079, "Item", progression=False, useful=False),
    "Super Repel": ItemData(200076, "Item", progression=False, useful=False),
    "Max Repel": ItemData(200077, "Item", progression=False, useful=False),
    "Sun Stone": ItemData(200080, "Item", progression=False, useful=False),
    "Moon Stone": ItemData(200081, "Item", progression=False, useful=True),
    "Fire Stone": ItemData(200082, "Item", progression=False, useful=True),
    "Thunder Stone": ItemData(200083, "Item", progression=False, useful=True),
    "Water Stone": ItemData(200084, "Item", progression=False, useful=True),
    "Leaf Stone": ItemData(200085, "Item", progression=False, useful=True),
    "Shiny Stone": ItemData(200107, "Item", progression=False, useful=True),
    "Dusk Stone": ItemData(200108, "Item", progression=False, useful=True),
    "Dawn Stone": ItemData(200109, "Item", progression=False, useful=True),
    "Oval Stone": ItemData(200110, "Item", progression=False, useful=True),
    "Tiny Mushroom": ItemData(200086, "Item", progression=False, useful=False),
    "Big Mushroom": ItemData(200087, "Item", progression=False, useful=False),
    "Pearl": ItemData(200088, "Item", progression=False, useful=False),
    "Big Pearl": ItemData(200089, "Item", progression=False, useful=False),
    "Stardust": ItemData(200090, "Item", progression=False, useful=False),
    "Star Piece": ItemData(200091, "Item", progression=False, useful=False),
    "Nugget": ItemData(200092, "Item", progression=False, useful=False),
    "Heart Scale": ItemData(200093, "Item", progression=False, useful=False),
    "Rare Bone": ItemData(200106, "Item", progression=False, useful=False),
    "Balm Mushroom": ItemData(200580, "Item", progression=False, useful=False),
    "Big Nugget": ItemData(200581, "Item", progression=False, useful=False),
    "Pearl String": ItemData(200582, "Item", progression=False, useful=False),
    "Comet Shard": ItemData(200583, "Item", progression=False, useful=False),

    # Key Items (Verified Gen 6 3DS RAM IDs from PKHeX ItemStorage6XY)
    "Dowsing Machine": ItemData(200471, "Item", progression=True, useful=False),
    "Roller Skates": ItemData(200643, "Item", progression=True, useful=False),
    "Poke Flute": ItemData(200651, "Item", progression=True, useful=False),
    "Power Plant Pass": ItemData(200695, "Item", progression=True, useful=True),
    "Mega Ring": ItemData(200696, "Item", progression=False, useful=True),
    "Intriguing Stone": ItemData(200697, "Item", progression=False, useful=False),
    "Elevator Key": ItemData(200700, "Item", progression=True, useful=True),
    "TMV Pass": ItemData(200701, "Item", progression=False, useful=False),
    "Honor of Kalos": ItemData(200702, "Item", progression=False, useful=False),
    "Bicycle": ItemData(200713, "Item", progression=False, useful=False),
    "Holo Caster": ItemData(200714, "Item", progression=False, useful=False),

    "Bright Powder": ItemData(200213, "Item", progression=False, useful=False),
    "White Herb": ItemData(200214, "Mega Stones", progression=False, useful=True),
    "Macho Brace": ItemData(200215, "Item", progression=False, useful=False),
    "Exp. Share": ItemData(200216, "Item", progression=False, useful=False),
    "Quick Claw": ItemData(200217, "Item", progression=False, useful=False),
    "Soothe Bell": ItemData(200218, "Item", progression=False, useful=False),
    "Mental Herb": ItemData(200219, "Item", progression=False, useful=False),
    "Choice Band": ItemData(200220, "Item", progression=False, useful=False),
    "King's Rock": ItemData(200221, "Item", progression=False, useful=False),
    "Silver Powder": ItemData(200222, "Item", progression=False, useful=False),
    "Amulet Coin": ItemData(200223, "Item", progression=False, useful=False),
    "Cleanse Tag": ItemData(200224, "Item", progression=False, useful=False),
    "Soul Dew": ItemData(200225, "Item", progression=False, useful=False),
    "Deep Sea Tooth": ItemData(200226, "Item", progression=False, useful=False),
    "Deep Sea Scale": ItemData(200227, "Item", progression=False, useful=False),
    "Smoke Ball": ItemData(200228, "Item", progression=False, useful=False),
    "Everstone": ItemData(200229, "Item", progression=False, useful=False),
    "Focus Band": ItemData(200230, "Item", progression=False, useful=False),
    "Lucky Egg": ItemData(200231, "Item", progression=False, useful=False),
    "Scope Lens": ItemData(200232, "Item", progression=False, useful=False),
    "Leftovers": ItemData(200234, "Item", progression=False, useful=False),
    "Dragon Scale": ItemData(200235, "Item", progression=False, useful=False),
    "Light Ball": ItemData(200236, "Item", progression=False, useful=False),
    "Soft Sand": ItemData(200237, "Item", progression=False, useful=False),
    "Hard Stone": ItemData(200238, "Item", progression=False, useful=True),
    "Miracle Seed": ItemData(200239, "Item", progression=False, useful=False),
    "Black Glasses": ItemData(200240, "Item", progression=False, useful=False),
    "Black Belt": ItemData(200241, "Item", progression=False, useful=False),
    "Magnet": ItemData(200242, "Item", progression=False, useful=False),
    "Mystic Water": ItemData(200243, "Item", progression=False, useful=False),
    "Sharp Beak": ItemData(200244, "Item", progression=False, useful=False),
    "Poison Barb": ItemData(200245, "Item", progression=False, useful=False),
    "Never-Melt Ice": ItemData(200246, "Item", progression=False, useful=False),
    "Spell Tag": ItemData(200247, "Item", progression=False, useful=False),
    "Twisted Spoon": ItemData(200248, "Item", progression=False, useful=False),
    "Charcoal": ItemData(200249, "Item", progression=False, useful=False),
    "Dragon Fang": ItemData(200250, "Item", progression=False, useful=False),
    "Silk Scarf": ItemData(200251, "Item", progression=False, useful=False),
    "Up-Grade": ItemData(200252, "Item", progression=False, useful=False),
    "Shell Bell": ItemData(200253, "Item", progression=False, useful=False),
    "Sea Incense": ItemData(200254, "Item", progression=False, useful=False),
    "Lax Incense": ItemData(200255, "Item", progression=False, useful=False),
    "Rocky Helmet": ItemData(200540, "Item", progression=False, useful=False),
    "Eviolite": ItemData(200538, "Mega Stones", progression=False, useful=True),
    "Choice Specs": ItemData(200297, "Item", progression=False, useful=False),
    "Choice Scarf": ItemData(200287, "Item", progression=False, useful=False),
    "Life Orb": ItemData(200270, "Item", progression=False, useful=False),
    "Toxic Orb": ItemData(200272, "Item", progression=False, useful=False),
    "Flame Orb": ItemData(200273, "Item", progression=False, useful=False),
    "Focus Sash": ItemData(200275, "Item", progression=False, useful=False),
    "Expert Belt": ItemData(200268, "Item", progression=False, useful=False),

    # HMs (Verified Gen 6 3DS RAM IDs from PKHeX ItemStorage6XY)
    "HM01 Cut": ItemData(200420, "HMs", progression=True, useful=False),
    "HM02 Fly": ItemData(200421, "HMs", progression=False, useful=True),
    "HM03 Surf": ItemData(200422, "HMs", progression=True, useful=False),
    "HM04 Strength": ItemData(200423, "HMs", progression=True, useful=False),
    "HM05 Waterfall": ItemData(200424, "HMs", progression=True, useful=False),

    # Mega Stones (Verified Gen 6 3DS RAM IDs from PKHeX text_Items_en)
    "Gengarite": ItemData(200656, "Mega Stones", progression=False, useful=True),
    "Gardevoirite": ItemData(200657, "Mega Stones", progression=False, useful=True),
    "Ampharosite": ItemData(200658, "Mega Stones", progression=False, useful=True),
    "Venusaurite": ItemData(200659, "Mega Stones", progression=False, useful=True),
    "Charizardite X": ItemData(200660, "Mega Stones", progression=False, useful=True),
    "Blastoisinite": ItemData(200661, "Mega Stones", progression=False, useful=True),
    "Mewtwonite X": ItemData(200662, "Mega Stones", progression=False, useful=True),
    "Mewtwonite Y": ItemData(200663, "Mega Stones", progression=False, useful=True),
    "Blazikenite": ItemData(200664, "Mega Stones", progression=False, useful=True),
    "Medichamite": ItemData(200665, "Mega Stones", progression=False, useful=True),
    "Houndoominite": ItemData(200666, "Mega Stones", progression=False, useful=True),
    "Aggronite": ItemData(200667, "Mega Stones", progression=False, useful=True),
    "Banettite": ItemData(200668, "Mega Stones", progression=False, useful=True),
    "Tyranitarite": ItemData(200669, "Mega Stones", progression=False, useful=True),
    "Scizorite": ItemData(200670, "Mega Stones", progression=False, useful=True),
    "Pinsirite": ItemData(200671, "Mega Stones", progression=False, useful=True),
    "Aerodactylite": ItemData(200672, "Mega Stones", progression=False, useful=True),
    "Lucarionite": ItemData(200673, "Mega Stones", progression=False, useful=True),
    "Abomasite": ItemData(200674, "Mega Stones", progression=False, useful=True),
    "Kangaskhanite": ItemData(200675, "Mega Stones", progression=False, useful=True),
    "Gyaradosite": ItemData(200676, "Mega Stones", progression=False, useful=True),
    "Absolite": ItemData(200677, "Mega Stones", progression=False, useful=True),
    "Charizardite Y": ItemData(200678, "Mega Stones", progression=False, useful=True),
    "Alakazamite": ItemData(200679, "Mega Stones", progression=False, useful=True),
    "Heracronite": ItemData(200680, "Mega Stones", progression=False, useful=True),
    "Mawilite": ItemData(200681, "Mega Stones", progression=False, useful=True),
    "Manectite": ItemData(200682, "Mega Stones", progression=False, useful=True),
    "Garchompite": ItemData(200683, "Mega Stones", progression=False, useful=True),

    # TMs (Verified Gen 6 3DS RAM IDs)
    "TM01 Hone Claws": ItemData(200328, "TMs", progression=False, useful=True),
    "TM02 Dragon Claw": ItemData(200329, "TMs", progression=False, useful=True),
    "TM03 Psyshock": ItemData(200330, "TMs", progression=False, useful=True),
    "TM04 Calm Mind": ItemData(200331, "TMs", progression=False, useful=True),
    "TM05 Roar": ItemData(200332, "TMs", progression=False, useful=True),
    "TM06 Toxic": ItemData(200333, "TMs", progression=False, useful=True),
    "TM07 Hail": ItemData(200334, "TMs", progression=False, useful=True),
    "TM08 Bulk Up": ItemData(200335, "TMs", progression=False, useful=True),
    "TM09 Venoshock": ItemData(200336, "TMs", progression=False, useful=True),
    "TM10 Hidden Power": ItemData(200337, "TMs", progression=False, useful=True),
    "TM11 Sunny Day": ItemData(200338, "TMs", progression=False, useful=True),
    "TM12 Taunt": ItemData(200339, "TMs", progression=False, useful=True),
    "TM13 Ice Beam": ItemData(200340, "TMs", progression=False, useful=True),
    "TM14 Blizzard": ItemData(200341, "TMs", progression=False, useful=True),
    "TM15 Hyper Beam": ItemData(200342, "TMs", progression=False, useful=True),
    "TM16 Light Screen": ItemData(200343, "TMs", progression=False, useful=True),
    "TM17 Protect": ItemData(200344, "TMs", progression=False, useful=True),
    "TM18 Rain Dance": ItemData(200345, "TMs", progression=False, useful=True),
    "TM19 Roost": ItemData(200346, "TMs", progression=False, useful=True),
    "TM20 Safeguard": ItemData(200347, "TMs", progression=False, useful=True),
    "TM21 Frustration": ItemData(200348, "TMs", progression=False, useful=True),
    "TM22 Solar Beam": ItemData(200349, "TMs", progression=False, useful=True),
    "TM23 Smack Down": ItemData(200350, "TMs", progression=False, useful=True),
    "TM24 Thunderbolt": ItemData(200351, "TMs", progression=False, useful=True),
    "TM25 Thunder": ItemData(200352, "TMs", progression=False, useful=True),
    "TM26 Earthquake": ItemData(200353, "TMs", progression=False, useful=True),
    "TM27 Return": ItemData(200354, "TMs", progression=False, useful=True),
    "TM28 Dig": ItemData(200355, "TMs", progression=False, useful=True),
    "TM29 Psychic": ItemData(200356, "TMs", progression=False, useful=True),
    "TM30 Shadow Ball": ItemData(200357, "TMs", progression=False, useful=True),
    "TM31 Brick Break": ItemData(200358, "TMs", progression=False, useful=True),
    "TM32 Double Team": ItemData(200359, "TMs", progression=False, useful=True),
    "TM33 Reflect": ItemData(200360, "TMs", progression=False, useful=True),
    "TM34 Sludge Wave": ItemData(200361, "TMs", progression=False, useful=True),
    "TM35 Flamethrower": ItemData(200362, "TMs", progression=False, useful=True),
    "TM36 Sludge Bomb": ItemData(200363, "TMs", progression=False, useful=True),
    "TM37 Sandstorm": ItemData(200364, "TMs", progression=False, useful=True),
    "TM38 Fire Blast": ItemData(200365, "TMs", progression=False, useful=True),
    "TM39 Rock Tomb": ItemData(200366, "TMs", progression=False, useful=True),
    "TM40 Aerial Ace": ItemData(200367, "TMs", progression=False, useful=True),
    "TM41 Torment": ItemData(200368, "TMs", progression=False, useful=True),
    "TM42 Facade": ItemData(200369, "TMs", progression=False, useful=True),
    "TM43 Flame Charge": ItemData(200370, "TMs", progression=False, useful=True),
    "TM44 Rest": ItemData(200371, "TMs", progression=False, useful=True),
    "TM45 Attract": ItemData(200372, "TMs", progression=False, useful=True),
    "TM46 Thief": ItemData(200373, "TMs", progression=False, useful=True),
    "TM47 Low Sweep": ItemData(200374, "TMs", progression=False, useful=True),
    "TM48 Round": ItemData(200375, "TMs", progression=False, useful=True),
    "TM49 Echoed Voice": ItemData(200376, "TMs", progression=False, useful=True),
    "TM50 Overheat": ItemData(200377, "TMs", progression=False, useful=True),
    "TM51 Steel Wing": ItemData(200378, "TMs", progression=False, useful=True),
    "TM52 Focus Blast": ItemData(200379, "TMs", progression=False, useful=True),
    "TM53 Energy Ball": ItemData(200380, "TMs", progression=False, useful=True),
    "TM54 False Swipe": ItemData(200381, "TMs", progression=False, useful=True),
    "TM55 Scald": ItemData(200382, "TMs", progression=False, useful=True),
    "TM56 Fling": ItemData(200383, "TMs", progression=False, useful=True),
    "TM57 Charge Beam": ItemData(200384, "TMs", progression=False, useful=True),
    "TM58 Sky Drop": ItemData(200385, "TMs", progression=False, useful=True),
    "TM59 Incinerate": ItemData(200386, "TMs", progression=False, useful=True),
    "TM60 Quash": ItemData(200387, "TMs", progression=False, useful=True),
    "TM61 Will-O-Wisp": ItemData(200388, "TMs", progression=False, useful=True),
    "TM62 Acrobatics": ItemData(200389, "TMs", progression=False, useful=True),
    "TM63 Embargo": ItemData(200390, "TMs", progression=False, useful=True),
    "TM64 Explosion": ItemData(200391, "TMs", progression=False, useful=True),
    "TM65 Shadow Claw": ItemData(200392, "TMs", progression=False, useful=True),
    "TM66 Payback": ItemData(200393, "TMs", progression=False, useful=True),
    "TM67 Retaliate": ItemData(200394, "TMs", progression=False, useful=True),
    "TM68 Giga Impact": ItemData(200395, "TMs", progression=False, useful=True),
    "TM69 Rock Polish": ItemData(200396, "TMs", progression=False, useful=True),
    "TM70 Flash": ItemData(200397, "TMs", progression=False, useful=True),
    "TM71 Stone Edge": ItemData(200398, "TMs", progression=False, useful=True),
    "TM72 Volt Switch": ItemData(200399, "TMs", progression=False, useful=True),
    "TM73 Thunder Wave": ItemData(200400, "TMs", progression=False, useful=True),
    "TM74 Gyro Ball": ItemData(200401, "TMs", progression=False, useful=True),
    "TM75 Swords Dance": ItemData(200402, "TMs", progression=False, useful=True),
    "TM76 Struggle Bug": ItemData(200403, "TMs", progression=False, useful=True),
    "TM77 Psych Up": ItemData(200404, "TMs", progression=False, useful=True),
    "TM78 Bulldoze": ItemData(200405, "TMs", progression=False, useful=True),
    "TM79 Frost Breath": ItemData(200406, "TMs", progression=False, useful=True),
    # TM80-TM92 move names were shifted and did not match the item ids, which
    # are correct (TM01-TM92 = game items 328-419, so 200407 really is TM80).
    # Players were told they had received a move that was not what landed in the
    # bag, and three moves appeared twice under two different TM numbers.
    # Gen VI TMs match Gen V except TM19, TM51, TM83 and TM88; corrected below
    # against that, and cross-checked with the TM names already used in
    # Locations.py (TM80 Rock Slide, TM81 X-Scissor, TM88 Sleep Talk).
    "TM80 Rock Slide": ItemData(200407, "TMs", progression=False, useful=True),
    "TM81 X-Scissor": ItemData(200408, "TMs", progression=False, useful=True),
    "TM82 Dragon Tail": ItemData(200409, "TMs", progression=False, useful=True),
    "TM83 Infestation": ItemData(200410, "TMs", progression=False, useful=True),
    "TM84 Poison Jab": ItemData(200411, "TMs", progression=False, useful=True),
    "TM85 Dream Eater": ItemData(200412, "TMs", progression=False, useful=True),
    "TM86 Grass Knot": ItemData(200413, "TMs", progression=False, useful=True),
    "TM87 Swagger": ItemData(200414, "TMs", progression=False, useful=True),
    "TM88 Sleep Talk": ItemData(200415, "TMs", progression=False, useful=True),
    "TM89 U-turn": ItemData(200416, "TMs", progression=False, useful=True),
    "TM90 Substitute": ItemData(200417, "TMs", progression=False, useful=True),
    "TM91 Flash Cannon": ItemData(200418, "TMs", progression=False, useful=True),
    "TM92 Trick Room": ItemData(200419, "TMs", progression=False, useful=True),
    "TM93 Wild Charge": ItemData(200618, "TMs", progression=False, useful=True),
    # Progression: Rock Smash is a field move in X/Y and gates roughly 17
    # item locations (Terminus Cave, Victory Road, Route 13/15, Lost Hotel).
    "TM94 Rock Smash": ItemData(200619, "TMs", progression=True, useful=True),
    "TM95 Snarl": ItemData(200620, "TMs", progression=False, useful=True),
    "TM96 Nature Power": ItemData(200690, "TMs", progression=False, useful=True),
    "TM97 Dark Pulse": ItemData(200691, "TMs", progression=False, useful=True),
    "TM98 Power-Up Punch": ItemData(200692, "TMs", progression=False, useful=True),
    "TM99 Dazzling Gleam": ItemData(200693, "TMs", progression=False, useful=True),
    "TM100 Confide": ItemData(200694, "TMs", progression=False, useful=True),
}

item_id_to_name: Dict[int, str] = {idata.code: iname for iname, idata in item_table.items()}
